apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: usg-itsm

commonLabels:
  app.kubernetes.io/part-of: usg-itsm

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - nats.yaml
  - keycloak.yaml
  - identity.yaml
  - ticketing.yaml
  - notification.yaml
  - gateway.yaml

configMapGenerator:
  - name: keycloak-realm
    files:
      - realm-usg-itsm.json=keycloak-realm.json

generatorOptions:
  disableNameSuffixHash: true
